import sys

#list
nums_squared_lc = [i ** 2 for i in range(10000)]

print(sys.getsizeof(nums_squared_lc))

#generator
nums_squared_gc = (i ** 2 for i in range(10000))
print(sys.getsizeof(nums_squared_gc))


# if were to sum all the number generated by list comrehension it would be faster
# but with generators it takes less memory. 
